/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import javax.swing.JOptionPane;
import tapioquitas.Nodes;

/**
 *
 * @author Rodrigo
 */
public class CreateCourses extends javax.swing.JFrame {

    /**
     * Creates new form Courses
     */
    private String sCourseName;//Nombre del curso
    private String sCourseCategory = "music";//Categoria
    private String sNumber;//Número celular
    private String sDescription;//DEscripción

    public CreateCourses() {
        initComponents();
        lblNempty.setVisible(false);
        lblPempty.setVisible(false);
        lblDempty.setVisible(false);
        btnEdit.setVisible(false);
        btnEdit.setVisible(false);//Oculta el boton editar
        btnRemove.setVisible(false);//Oculta el boton remove
        if (Login.UsersList.nActiveUser.getiIdexCourse() != 0) {//Verifica si el usuario tiene un curso
            btnRemove.setVisible(true);
            btnEdit.setVisible(true);
            txtName.setText(Login.CoursesList.nUserCourse.getsCourseName());
            txtPhone.setText(Login.CoursesList.nUserCourse.getsNumber());
            txaDescrip.setText(Login.CoursesList.nUserCourse.getsDescription());
            btnCreate.setText("Save");
            btnCancel.setText("Back");
            lblTitle.setText("Your course");
            editable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescrip = new javax.swing.JTextArea();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblDempty = new javax.swing.JLabel();
        lblNempty = new javax.swing.JLabel();
        lblPempty = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setMaximumSize(new java.awt.Dimension(600, 600));
        jLabel2.setMinimumSize(new java.awt.Dimension(600, 600));
        jLabel2.setPreferredSize(new java.awt.Dimension(600, 600));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Name of your course:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 140, 14);

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(180, 100, 172, 20);

        lblTitle.setText("Create your course");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(214, 11, 168, 31);

        lblCategory.setText("Category:");
        getContentPane().add(lblCategory);
        lblCategory.setBounds(30, 130, 70, 14);

        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Music", "Dance", "School", "Visual art" }));
        cbCategory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cbCategory);
        cbCategory.setBounds(120, 130, 71, 22);

        lblPhoneNumber.setText("Phone number:");
        getContentPane().add(lblPhoneNumber);
        lblPhoneNumber.setBounds(30, 170, 90, 14);

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });
        getContentPane().add(txtPhone);
        txtPhone.setBounds(130, 170, 172, 20);

        lblDescription.setText("Description:");
        getContentPane().add(lblDescription);
        lblDescription.setBounds(30, 200, 80, 14);

        txaDescrip.setColumns(20);
        txaDescrip.setRows(5);
        txaDescrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txaDescripKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txaDescrip);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 220, 482, 200);

        btnCreate.setText("Create course");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate);
        btnCreate.setBounds(90, 460, 120, 23);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(330, 460, 147, 23);

        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(30, 70, 50, 19);

        lblDempty.setForeground(new java.awt.Color(204, 0, 0));
        lblDempty.setText("Field is Empty");
        getContentPane().add(lblDempty);
        lblDempty.setBounds(240, 440, 65, 14);

        lblNempty.setForeground(new java.awt.Color(204, 0, 0));
        lblNempty.setText("Field is Empty");
        getContentPane().add(lblNempty);
        lblNempty.setBounds(370, 100, 65, 14);

        lblPempty.setForeground(new java.awt.Color(204, 0, 0));
        lblPempty.setText("Field is Empty");
        getContentPane().add(lblPempty);
        lblPempty.setBounds(340, 170, 65, 14);

        btnRemove.setText("Remove course");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(207, 500, 130, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\erika\\Documents\\proyecto netbans\\3.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(600, 600));
        jLabel3.setMinimumSize(new java.awt.Dimension(600, 600));
        jLabel3.setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 620, 580);
        jLabel3.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed
        sCourseCategory = (String) cbCategory.getSelectedItem();
    }//GEN-LAST:event_cbCategoryActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        sCourseName = txtName.getText();
        sNumber = txtPhone.getText();
        sDescription = txaDescrip.getText();

        //Verifica si el usuario tiene un curso
        if (Login.UsersList.nActiveUser.getiIdexCourse() != 0) {//Si tiene curso, edita el curso
            Login.CoursesList.nUserCourse.setsDescription(sDescription);
            Login.CoursesList.nUserCourse.setsNumber(sNumber);
            Login.CoursesList.nUserCourse.setsCourseName(sCourseName);
            JOptionPane.showMessageDialog(this, "course Saved", "Done!", JOptionPane.INFORMATION_MESSAGE);
        } else {//Si no tiene curso, crea uuno nuevo
            Login.UsersList.nActiveUser.setiIdexCourse((Login.iCountIndex) + 1);
            Nodes nNode = new Nodes(Login.sName, Login.sLastname, (Login.iCountIndex) + 1, sCourseCategory.toLowerCase(), sCourseName, sNumber, sDescription);
            Login.CoursesList.add(nNode);
            Login.CoursesList.nUserCourse = nNode;
            JOptionPane.showMessageDialog(this, "course created", "Done!", JOptionPane.INFORMATION_MESSAGE);
            Login.saveUser();
            Login.saveCourser();
        }
        dispose();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Home hHome = new Home();
        hHome.setVisible(true);
        hHome.setLocationRelativeTo(this);
    }//GEN-LAST:event_formWindowClosed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        editable(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed

        int iDialogResult = JOptionPane.showConfirmDialog(this, "Remove course?", "Confirm", JOptionPane.OK_CANCEL_OPTION);
        if (iDialogResult == 0) {
            Login.CoursesList.removeCourse();
            JOptionPane.showMessageDialog(this, "Course removed", "Done!", JOptionPane.INFORMATION_MESSAGE);
            Login.UsersList.nActiveUser.setiIdexCourse(0);
            Login.hHome.repintar();
            Login.saveUser();
            Login.saveCourser();
        }
        dispose();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        lblNempty.setVisible(false);
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        lblNempty.setVisible(false);
    }//GEN-LAST:event_txtPhoneKeyTyped

    private void txaDescripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txaDescripKeyTyped
        lblDempty.setVisible(false);
    }//GEN-LAST:event_txaDescripKeyTyped

    private void editable(boolean blEdit) {
        btnCreate.setEnabled(blEdit);
        txtName.setEditable(blEdit);
        txtPhone.setEditable(blEdit);
        //cbCategory.setSelectedIndex(2);
        cbCategory.setEnabled(false);
        txaDescrip.setEditable(blEdit);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDempty;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblNempty;
    private javax.swing.JLabel lblPempty;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txaDescrip;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
