/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Rodrigo
 */
public class DataCourse extends javax.swing.JFrame {

    /**
     * Creates new form DataCourse
     */
    public DataCourse() {
        initComponents();
    }

    public DataCourse(String[] asData) {
        initComponents();
        this.lblTitle.setText(asData[0]);
        this.lblCat.setText(asData[1]);
        this.lblfullname.setText(asData[2]);
        this.lblNumber.setText(asData[3]);
        this.jLabel1.setText(asData[4]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCat = new javax.swing.JLabel();
        lblfullname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 350));
        setMinimumSize(new java.awt.Dimension(400, 350));
        setPreferredSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        btnCancel.setText("Back");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(120, 260, 147, 23);

        lblTitle.setText("Create your course");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(130, 50, 190, 31);

        lblCategory.setText("Category:");
        getContentPane().add(lblCategory);
        lblCategory.setBounds(71, 84, 70, 14);

        lblPhoneNumber.setText("Phone number:");
        getContentPane().add(lblPhoneNumber);
        lblPhoneNumber.setBounds(70, 130, 90, 14);

        lblDescription.setText("Description:");
        getContentPane().add(lblDescription);
        lblDescription.setBounds(49, 178, 280, 14);

        lblName.setText("Name:");
        getContentPane().add(lblName);
        lblName.setBounds(71, 109, 70, 14);

        lblNumber.setText("jLabel1");
        getContentPane().add(lblNumber);
        lblNumber.setBounds(171, 134, 143, 14);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 200, 261, 40);

        lblCat.setText("jLabel2");
        getContentPane().add(lblCat);
        lblCat.setBounds(159, 84, 100, 14);

        lblfullname.setText("jLabel2");
        getContentPane().add(lblfullname);
        lblfullname.setBounds(159, 109, 150, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\erika\\Documents\\proyecto netbans\\3.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel2.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 410, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblfullname;
    // End of variables declaration//GEN-END:variables
}
