/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import java.util.Calendar;
import javax.swing.JOptionPane;
import tapioquitas.Nodes;
import tapioquitas.Tapioquitas;

/**
 *
 * @author Rodrigo
 */
class Sign_up extends javax.swing.JFrame {

    /**
     * Creates new form Sign_up
     */
    String sName;
    String sLastName;
    String sGender = null;
    String sEmail;
    String sPassword;
    String sConPassword;
    int[] aiBirth = new int[3];
    boolean bPassMatch;

    public Sign_up() {
        initComponents();
        setLocationRelativeTo(null);
        //Ocultar las imagenes y texto de error
        imgName.setVisible(false);
        imgLast.setVisible(false);
        imgGender.setVisible(false);
        imgEmail.setVisible(false);
        imgPassword.setVisible(false);
        imgConPassword.setVisible(false);
        lblNotMatch.setVisible(false);
        lblEmpty.setVisible(false);

        //Crear los datos de los combo box
        //Dia
        for (int i = 1; i <= 31; i++) {
            cbDay.addItem(Integer.toString(i));
        }
        //Mes
        for (int i = 1; i <= 12; i++) {
            cbMonth.addItem(Integer.toString(i));
        }
        //Año
        for (int i = Calendar.getInstance().get(Calendar.YEAR); i >= 1900; i--) {
            cbYear.addItem(Integer.toString(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblBrith = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        rbtMale = new javax.swing.JRadioButton();
        rbtFemale = new javax.swing.JRadioButton();
        txtName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblConPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtConPassword = new javax.swing.JPasswordField();
        btnCreate = new javax.swing.JButton();
        cbMonth = new javax.swing.JComboBox<>();
        cbYear = new javax.swing.JComboBox<>();
        cbDay = new javax.swing.JComboBox<>();
        lblNotMatch = new javax.swing.JLabel();
        imgName = new javax.swing.JLabel();
        imgLast = new javax.swing.JLabel();
        imgEmail = new javax.swing.JLabel();
        imgPassword = new javax.swing.JLabel();
        imgConPassword = new javax.swing.JLabel();
        imgGender = new javax.swing.JLabel();
        lblEmpty = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        lblName.setText("First name:");
        getContentPane().add(lblName);
        lblName.setBounds(60, 50, 80, 14);

        lblLastName.setText("Last name:");
        getContentPane().add(lblLastName);
        lblLastName.setBounds(60, 90, 90, 14);

        lblBrith.setText("Birth date: ");
        getContentPane().add(lblBrith);
        lblBrith.setBounds(60, 150, 70, 14);

        lblGender.setText("Gender:");
        getContentPane().add(lblGender);
        lblGender.setBounds(60, 210, 80, 14);

        btnGroup.add(rbtMale);
        rbtMale.setText("Male");
        rbtMale.setContentAreaFilled(false);
        rbtMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtMaleMouseClicked(evt);
            }
        });
        rbtMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMaleActionPerformed(evt);
            }
        });
        getContentPane().add(rbtMale);
        rbtMale.setBounds(160, 210, 70, 23);

        btnGroup.add(rbtFemale);
        rbtFemale.setText("Female");
        rbtFemale.setContentAreaFilled(false);
        rbtFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtFemaleMouseClicked(evt);
            }
        });
        rbtFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(rbtFemale);
        rbtFemale.setBounds(240, 210, 80, 23);

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(160, 50, 165, 20);

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });
        getContentPane().add(txtLastName);
        txtLastName.setBounds(160, 90, 165, 20);

        lblEmail.setText("Email address:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(60, 260, 90, 14);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(60, 290, 267, 24);

        lblPassword.setText("Password:");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(60, 330, 70, 14);

        lblConPassword.setText("Confirm password");
        getContentPane().add(lblConPassword);
        lblConPassword.setBounds(60, 400, 260, 14);

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(60, 360, 267, 24);

        txtConPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtConPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConPasswordActionPerformed(evt);
            }
        });
        txtConPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConPasswordKeyTyped(evt);
            }
        });
        getContentPane().add(txtConPassword);
        txtConPassword.setBounds(60, 430, 267, 20);

        btnCreate.setText("Create account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate);
        btnCreate.setBounds(40, 510, 130, 23);

        cbMonth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonthActionPerformed(evt);
            }
        });
        getContentPane().add(cbMonth);
        cbMonth.setBounds(200, 150, 40, 22);

        cbYear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearActionPerformed(evt);
            }
        });
        getContentPane().add(cbYear);
        cbYear.setBounds(260, 150, 40, 22);

        cbDay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDayActionPerformed(evt);
            }
        });
        getContentPane().add(cbDay);
        cbDay.setBounds(140, 150, 40, 22);

        lblNotMatch.setBackground(new java.awt.Color(204, 204, 204));
        lblNotMatch.setForeground(new java.awt.Color(0, 0, 153));
        lblNotMatch.setText("Passwords not match");
        getContentPane().add(lblNotMatch);
        lblNotMatch.setBounds(80, 460, 198, 34);

        imgName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wrong.png"))); // NOI18N
        getContentPane().add(imgName);
        imgName.setBounds(330, 50, 30, 20);

        imgLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wrong.png"))); // NOI18N
        getContentPane().add(imgLast);
        imgLast.setBounds(330, 90, 40, 30);

        imgEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wrong.png"))); // NOI18N
        getContentPane().add(imgEmail);
        imgEmail.setBounds(340, 290, 24, 27);

        imgPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wrong.png"))); // NOI18N
        getContentPane().add(imgPassword);
        imgPassword.setBounds(340, 360, 24, 24);

        imgConPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wrong.png"))); // NOI18N
        getContentPane().add(imgConPassword);
        imgConPassword.setBounds(340, 430, 24, 24);

        imgGender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wrong.png"))); // NOI18N
        getContentPane().add(imgGender);
        imgGender.setBounds(320, 210, 24, 24);

        lblEmpty.setBackground(new java.awt.Color(204, 204, 204));
        lblEmpty.setForeground(new java.awt.Color(0, 0, 153));
        lblEmpty.setText("Fields empty");
        getContentPane().add(lblEmpty);
        lblEmpty.setBounds(180, 540, 60, 32);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(270, 510, 119, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\erika\\Documents\\proyecto netbans\\3.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 520, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void rbtMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtMaleActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        //Capturar datos de los textfields
        sName = txtName.getText();//Nombre
        sLastName = txtLastName.getText();//Apellido
        sEmail = txtEmail.getText();//Email
        sPassword = txtPassword.getText();//Contraseña
        sConPassword = txtConPassword.getText();//Confirmar contraseña
        bPassMatch = true;//Guarda si las contraseñas coinciden

        //Captura valor de los radio botton
        if (rbtFemale.isSelected()) {//Mujer
            sGender = "Female";
        }
        if (rbtMale.isSelected()) {//Hombre
            sGender = "Male";
        }

        //Guardar los datos
        if (Okey(sName, sLastName, sEmail, sGender, sPassword, sConPassword) && bPassMatch) {//Comprueba que se ingresaron todos los datos
            lblEmpty.setVisible(false);
            Login.UsersList.add(new Nodes(sName, sLastName, sGender, sEmail, sPassword, aiBirth, 0));
            JOptionPane.showMessageDialog(this, "Account created", "Done!", JOptionPane.INFORMATION_MESSAGE);
            Login.saveUser();
            dispose();
        }

    }//GEN-LAST:event_btnCreateActionPerformed

    private void cbDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDayActionPerformed
        aiBirth[0] = Integer.parseInt((String) cbDay.getSelectedItem());

    }//GEN-LAST:event_cbDayActionPerformed

    private void cbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonthActionPerformed
        aiBirth[1] = Integer.parseInt((String) cbMonth.getSelectedItem());
    }//GEN-LAST:event_cbMonthActionPerformed

    private void cbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearActionPerformed
        aiBirth[2] = Integer.parseInt((String) cbYear.getSelectedItem());
    }//GEN-LAST:event_cbYearActionPerformed

    private void rbtFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtFemaleActionPerformed

    private void txtConPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConPasswordActionPerformed

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        imgName.setVisible(false);
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        imgLast.setVisible(false);
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void rbtMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtMaleMouseClicked
        imgGender.setVisible(false);
    }//GEN-LAST:event_rbtMaleMouseClicked

    private void rbtFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtFemaleMouseClicked
        imgGender.setVisible(false);
    }//GEN-LAST:event_rbtFemaleMouseClicked

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        imgEmail.setVisible(false);
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        imgPassword.setVisible(false);
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtConPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConPasswordKeyTyped
        lblNotMatch.setVisible(false);
        imgConPassword.setVisible(false);
    }//GEN-LAST:event_txtConPasswordKeyTyped

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        Tapioquitas.lLogin.setVisible(true);
        Tapioquitas.lLogin.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Tapioquitas.lLogin.setVisible(true);
        Tapioquitas.lLogin.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_formWindowClosed

    //Metodo para comprobar que se ingresaron todos los datos
    private boolean Okey(String Name, String LastName, String Email, String Gender, String Password, String ConPassword) {
        boolean bAllOkey = true;
        if (Name.equals("")) {
            imgName.setVisible(true);
            bAllOkey = false;
        }
        if (LastName.equals("")) {
            imgLast.setVisible(true);
            bAllOkey = false;
        }
        if (Email.equals("")) {
            imgEmail.setVisible(true);
            bAllOkey = false;
        }
        if (Gender == null) {
            imgGender.setVisible(true);
            bAllOkey = false;
        }
        if (Password.equals("")) {
            imgPassword.setVisible(true);
            bAllOkey = false;
        }

        if (!(Password.equals(txtConPassword.getText()))) {
            lblNotMatch.setVisible(true);
            imgConPassword.setVisible(true);
            bPassMatch = false;
        }
        if (!bAllOkey) {
            lblEmpty.setVisible(true);
        }
        return bAllOkey;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JComboBox<String> cbDay;
    private javax.swing.JComboBox<String> cbMonth;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JLabel imgConPassword;
    private javax.swing.JLabel imgEmail;
    private javax.swing.JLabel imgGender;
    private javax.swing.JLabel imgLast;
    private javax.swing.JLabel imgName;
    private javax.swing.JLabel imgPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBrith;
    private javax.swing.JLabel lblConPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpty;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNotMatch;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JRadioButton rbtFemale;
    private javax.swing.JRadioButton rbtMale;
    private javax.swing.JPasswordField txtConPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
