/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class ViewCourse extends javax.swing.JPanel {

    /**
     * Creates new form ViewCourse
     */
    private String[] asString = new String[6];
    public static DataCourse dcData;
    int iIndex;

    public ViewCourse() {
        setResizable(false);
        initComponents();

    }

    public ViewCourse(String[] asData) {
        initComponents();
        btnErase.setVisible(false);
        if (Login.sName.equals("Admin")) {
            btnErase.setVisible(true);
        }
        this.lblTitle.setText(asData[0]);
        this.lblCategory2.setText(asData[1]);
        this.lblName.setText(asData[2]);
        iIndex = Integer.parseInt(asData[5]);
        for (int i = 0; i < asData.length; i++) {
            asString[i] = asData[i];
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCategory2 = new javax.swing.JLabel();
        btnSeeMore = new javax.swing.JButton();
        btnErase = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 215, 246), 2, true));

        lblTitle.setText("Las locas aventuras de las tapiocas");

        lblCategory.setText("Category:");

        lblName.setText("Rodrigo Reyes");

        lblCategory2.setText("Music");

        btnSeeMore.setForeground(new java.awt.Color(0, 0, 255));
        btnSeeMore.setText("See more...");
        btnSeeMore.setBorder(null);
        btnSeeMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeMoreActionPerformed(evt);
            }
        });

        btnErase.setText("Remove");
        btnErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnErase, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeeMore, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCategory)
                                .addGap(6, 6, 6)
                                .addComponent(lblCategory2))
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory)
                    .addComponent(lblCategory2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeeMore)
                    .addComponent(btnErase, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeeMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeMoreActionPerformed
        dcData = new DataCourse(asString);
        dcData.setVisible(true);
        dcData.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnSeeMoreActionPerformed

    private void btnEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraseActionPerformed
        int iDialogResult = JOptionPane.showConfirmDialog(this, "Remove course?", "Confirm", JOptionPane.OK_CANCEL_OPTION);
        if (iDialogResult == 0) {
            Login.CoursesList.LoginSearchCourse(iIndex);
            Login.CoursesList.removeCourse();
            Login.UsersList.LoginSearchCourse(iIndex);
            Login.UsersList.nUserCourse.setiIdexCourse(0);
            Login.CoursesList.printList();
            System.out.println("");
            Login.UsersList.printList();
            System.out.println(Login.iCountIndex);
            //Login.saveCourser();
            //Login.saveUser();
            JOptionPane.showMessageDialog(this, "Course removed", "Done!", JOptionPane.INFORMATION_MESSAGE);
            Login.hHome.panel.remove(this);
            Login.hHome.repintar();
        }
    }//GEN-LAST:event_btnEraseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnErase;
    private javax.swing.JButton btnSeeMore;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCategory2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    private void setResizable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
